module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.89,True,2022-10-26T07:00:15,,
cowidev.vax.batch.australia,1.92,True,2022-10-26T07:00:13,,
cowidev.vax.batch.austria,2.52,True,2022-10-26T07:00:14,,
cowidev.vax.batch.belgium,2.46,True,2022-10-26T07:00:14,,
cowidev.vax.batch.bolivia,2.41,True,2022-10-26T07:00:14,,
cowidev.vax.batch.canada,6.28,True,2022-10-26T07:00:19,,
cowidev.vax.batch.chile,0.91,True,2022-10-26T07:00:14,,
cowidev.vax.batch.czechia,4.09,True,2022-10-26T07:00:18,,
cowidev.vax.batch.denmark,4.52,True,2022-10-26T07:00:18,,
cowidev.vax.batch.ecdc,60.07,False,2022-10-26T07:04:28,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fbd7204fa30>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbd7204fa30>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 492, in main
    ECDC().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 482, in export
    df = self.read().pipe(self.pipe_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/ecdc.py"", line 117, in read
    df = read_csv_from_url(self.source_url, timeout=30)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 55, in read_csv_from_url
    download_file_from_url(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 80, in download_file_from_url
    r = requests.get(url, stream=True, timeout=timeout, verify=verify)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbd7204fa30>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))
","HTTPSConnectionPool(host='opendata.ecdc.europa.eu', port=443): Max retries exceeded with url: /covid19/vaccine_tracker/csv/data.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbd7204fa30>, 'Connection to opendata.ecdc.europa.eu timed out. (connect timeout=30)'))"
cowidev.vax.batch.ecuador,1.74,True,2022-10-26T07:00:17,,
cowidev.vax.batch.estonia,0.79,True,2022-10-26T07:00:18,,
cowidev.vax.batch.france,0.43,True,2022-10-26T07:00:18,,
cowidev.vax.batch.germany,1.73,True,2022-10-26T07:00:19,,
cowidev.vax.batch.greece,2.94,True,2022-10-26T07:00:21,,
cowidev.vax.batch.hong_kong,13.24,True,2022-10-26T07:00:31,,
cowidev.vax.batch.indonesia,,,2022-10-26T07:00:19,,
cowidev.vax.batch.ireland,0.39,True,2022-10-26T07:00:20,,
cowidev.vax.batch.israel,11.15,True,2022-10-26T07:00:31,,
cowidev.vax.batch.italy,10.93,True,2022-10-26T07:00:31,,
cowidev.vax.batch.japan,0.53,False,2022-10-26T07:04:28,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 236, in main
    Japan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 220, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 156, in read
    df_latest = self.read_latest().pipe(self.pipe_latest)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 88, in read_latest
    dfs.append(self._read_xlsx(self.source_url, self.sheets, self.metrics))
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 97, in _read_xlsx
    xlsx = pd.ExcelFile(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1191, in __init__
    ext = inspect_excel_format(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1070, in inspect_excel_format
    with get_handle(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 609, in get_handle
    ioargs = _get_filepath_or_buffer(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 312, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 214, in urlopen
    return opener.open(url, data, timeout)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 523, in open
    response = meth(req, response)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 632, in http_response
    response = self.parent.error(
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 561, in error
    return self._call_chain(*args)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 494, in _call_chain
    result = func(*args)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
",HTTP Error 404: Not Found
cowidev.vax.batch.jersey,0.66,True,2022-10-26T07:00:31,,
cowidev.vax.batch.latvia,18.84,True,2022-10-26T07:00:49,,
cowidev.vax.batch.lithuania,2.06,True,2022-10-26T07:00:33,,
cowidev.vax.batch.luxembourg,1.93,True,2022-10-26T07:00:33,,
cowidev.vax.batch.malaysia,0.61,True,2022-10-26T07:00:32,,
cowidev.vax.batch.malta,0.89,True,2022-10-26T07:00:33,,
cowidev.vax.batch.netherlands,,,2022-10-26T07:00:33,,
cowidev.vax.batch.new_zealand,15.87,True,2022-10-26T07:00:49,,
cowidev.vax.batch.norway,0.37,True,2022-10-26T07:00:33,,
cowidev.vax.batch.peru,10.0,True,2022-10-26T07:00:43,,
cowidev.vax.batch.portugal,,,2022-10-26T07:00:33,,
cowidev.vax.batch.romania,13.83,True,2022-10-26T07:00:47,,
cowidev.vax.batch.saudi_arabia,4.72,True,2022-10-26T07:00:48,,
cowidev.vax.batch.singapore,1.06,True,2022-10-26T07:00:48,,
cowidev.vax.batch.slovakia,37.14,True,2022-10-26T07:01:25,,
cowidev.vax.batch.slovenia,0.6,True,2022-10-26T07:00:49,,
cowidev.vax.batch.south_korea,36.78,True,2022-10-26T07:01:25,,
cowidev.vax.batch.spc,16.25,True,2022-10-26T07:01:05,,
cowidev.vax.batch.sweden,12.32,True,2022-10-26T07:01:02,,
cowidev.vax.batch.switzerland,41.3,True,2022-10-26T07:01:43,,
cowidev.vax.batch.trinidad_and_tobago,1.7,True,2022-10-26T07:01:07,,
cowidev.vax.batch.ukraine,,,2022-10-26T07:01:07,,
cowidev.vax.batch.united_kingdom,8.0,True,2022-10-26T07:01:15,,
cowidev.vax.batch.united_states,21.83,True,2022-10-26T07:01:37,,
cowidev.vax.batch.uruguay,3.58,True,2022-10-26T07:01:20,,
cowidev.vax.batch.zimbabwe,1.14,True,2022-10-26T07:01:21,,
cowidev.vax.incremental.africacdc,,,2022-10-26T07:01:21,,
cowidev.vax.incremental.antigua_barbuda,,,2022-10-26T07:01:21,,
cowidev.vax.incremental.aruba,1.5,True,2022-10-26T07:01:22,,
cowidev.vax.incremental.azerbaijan,,,2022-10-26T07:01:22,,
cowidev.vax.incremental.bahrain,2.77,True,2022-10-26T07:01:25,,
cowidev.vax.incremental.bangladesh,19.72,True,2022-10-26T07:01:45,,
cowidev.vax.incremental.barbados,,,2022-10-26T07:01:25,,
cowidev.vax.incremental.brazil,0.06,True,2022-10-26T07:01:25,,
cowidev.vax.incremental.bulgaria,0.89,True,2022-10-26T07:01:26,,
cowidev.vax.incremental.china,40.07,True,2022-10-26T07:02:06,,
cowidev.vax.incremental.costa_rica,,,2022-10-26T07:01:26,,
cowidev.vax.incremental.croatia,0.13,True,2022-10-26T07:01:26,,
cowidev.vax.incremental.cuba,2.1,True,2022-10-26T07:01:28,,
cowidev.vax.incremental.curacao,0.48,True,2022-10-26T07:01:29,,
cowidev.vax.incremental.cyprus,0.75,True,2022-10-26T07:01:29,,
cowidev.vax.incremental.dominican_republic,9.02,True,2022-10-26T07:01:38,,
cowidev.vax.incremental.el_salvador,0.72,True,2022-10-26T07:01:37,,
cowidev.vax.incremental.faeroe_islands,0.39,True,2022-10-26T07:01:38,,
cowidev.vax.incremental.fiji,0.0,True,2022-10-26T07:01:38,,
cowidev.vax.incremental.finland,0.23,True,2022-10-26T07:01:38,,
cowidev.vax.incremental.gabon,,,2022-10-26T07:01:38,,
cowidev.vax.incremental.georgia,0.55,True,2022-10-26T07:01:38,,
cowidev.vax.incremental.greenland,0.49,False,2022-10-26T07:04:29,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 74, in main
    Greenland().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 61, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 18, in read
    data = self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 22, in _parse_data
    return {**self._parse_data_metrics(soup), **self._parse_data_date(soup)}
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 26, in _parse_data_metrics
    dose_1 = clean_count(re.search(r""Innuttaasut ([\d\.]+)"", counters[1].parent.find_all(""dd"")[-1].text).group(1))
IndexError: list index out of range
",list index out of range
cowidev.vax.incremental.guatemala,,,2022-10-26T07:01:38,,
cowidev.vax.incremental.guernsey,0.21,False,2022-10-26T07:04:29,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 61, in main
    Guernsey().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 50, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 15, in read
    df = self.parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 31, in parse_data
    ds.loc[ds[0] == ""Total doses"", 1].values[0].replace(""*"", """"),
IndexError: index 0 is out of bounds for axis 0 with size 0
",index 0 is out of bounds for axis 0 with size 0
cowidev.vax.incremental.hungary,1.17,True,2022-10-26T07:01:40,,
cowidev.vax.incremental.iceland,0.23,True,2022-10-26T07:01:39,,
cowidev.vax.incremental.india,0.92,True,2022-10-26T07:01:40,,
cowidev.vax.incremental.iran,,,2022-10-26T07:01:40,,
cowidev.vax.incremental.isle_of_man,0.41,True,2022-10-26T07:01:40,,
cowidev.vax.incremental.jamaica,1.94,True,2022-10-26T07:01:42,,
cowidev.vax.incremental.kazakhstan,13.3,True,2022-10-26T07:01:54,,
cowidev.vax.incremental.kosovo,1.39,True,2022-10-26T07:01:44,,
cowidev.vax.incremental.kyrgyzstan,1.75,True,2022-10-26T07:01:45,,
cowidev.vax.incremental.laos,2.35,True,2022-10-26T07:01:46,,
cowidev.vax.incremental.macao,19.73,False,2022-10-26T07:04:49,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 86, in main
    Macao().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 72, in export
    data = self.read()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 20, in read
    elem = driver.find_element_by_partial_link_text(""Weekly Bulletin on COVID-19"")
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 462, in find_element_by_partial_link_text
    return self.find_element(by=By.PARTIAL_LINK_TEXT, value=link_text)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {""method"":""partial link text"",""selector"":""Weekly Bulletin on COVID-19""}
  (Session info: headless chrome=106.0.5249.119)

","Message: no such element: Unable to locate element: {""method"":""partial link text"",""selector"":""Weekly Bulletin on COVID-19""}
  (Session info: headless chrome=106.0.5249.119)
"
cowidev.vax.incremental.moldova,,,2022-10-26T07:01:45,,
cowidev.vax.incremental.monaco,43.19,True,2022-10-26T07:02:28,,
cowidev.vax.incremental.mongolia,0.47,True,2022-10-26T07:01:46,,
cowidev.vax.incremental.montenegro,0.11,True,2022-10-26T07:01:46,,
cowidev.vax.incremental.morocco,,,2022-10-26T07:01:46,,
cowidev.vax.incremental.myanmar,,,2022-10-26T07:01:46,,
cowidev.vax.incremental.nepal,,,2022-10-26T07:01:46,,
cowidev.vax.incremental.north_macedonia,,,2022-10-26T07:01:46,,
cowidev.vax.incremental.northern_cyprus,0.6,True,2022-10-26T07:01:47,,
cowidev.vax.incremental.paho,80.36,False,2022-10-26T07:06:09,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 191, in main
    PAHO().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 186, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 57, in _parse_data
    filename = self._get_downloaded_filename()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 110, in _get_downloaded_filename
    return max(files, key=os.path.getctime)
ValueError: max() arg is an empty sequence
",max() arg is an empty sequence
cowidev.vax.incremental.pakistan,1.44,True,2022-10-26T07:01:55,,
cowidev.vax.incremental.philippines,,,2022-10-26T07:01:55,,
cowidev.vax.incremental.playground_mojmir,4.88,True,2022-10-26T07:02:00,,
cowidev.vax.incremental.poland,0.33,True,2022-10-26T07:02:00,,
cowidev.vax.incremental.qatar,,,2022-10-26T07:02:00,,
cowidev.vax.incremental.russia,0.44,False,2022-10-26T07:06:09,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 80, in main
    Russia().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 66, in export
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-10-26T07:02:01,,
cowidev.vax.incremental.serbia,9.01,True,2022-10-26T07:02:10,,
cowidev.vax.incremental.south_africa,7.4,True,2022-10-26T07:02:12,,
cowidev.vax.incremental.spain,8.48,True,2022-10-26T07:02:14,,
cowidev.vax.incremental.sri_lanka,,,2022-10-26T07:02:10,,
cowidev.vax.incremental.suriname,14.05,True,2022-10-26T07:02:24,,
cowidev.vax.incremental.taiwan,6.0,True,2022-10-26T07:02:18,,
cowidev.vax.incremental.thailand,4.1,True,2022-10-26T07:02:18,,
cowidev.vax.incremental.turkey,2.46,True,2022-10-26T07:02:21,,
cowidev.vax.incremental.united_arab_emirates,,,2022-10-26T07:02:18,,
cowidev.vax.incremental.vietnam,,,2022-10-26T07:02:18,,
cowidev.vax.incremental.who,4.8,True,2022-10-26T07:02:23,,
cowidev.vax.incremental.zambia,1.39,True,2022-10-26T07:02:22,,
