module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,11.77,True,2022-12-27T07:00:16,,
cowidev.vax.batch.australia,135.82,True,2022-12-27T07:02:20,,
cowidev.vax.batch.austria,11.45,True,2022-12-27T07:00:16,,
cowidev.vax.batch.belgium,12.67,True,2022-12-27T07:00:17,,
cowidev.vax.batch.bolivia,4.98,True,2022-12-27T07:00:10,,
cowidev.vax.batch.canada,31.29,True,2022-12-27T07:00:36,,
cowidev.vax.batch.chile,6.47,True,2022-12-27T07:00:11,,
cowidev.vax.batch.czechia,31.74,True,2022-12-27T07:00:36,,
cowidev.vax.batch.denmark,126.04,True,2022-12-27T07:02:11,,
cowidev.vax.batch.ecdc,142.12,True,2022-12-27T07:02:27,,
cowidev.vax.batch.ecuador,,,2022-12-27T07:00:05,,
cowidev.vax.batch.estonia,0.66,True,2022-12-27T07:00:05,,
cowidev.vax.batch.france,5.64,True,2022-12-27T07:00:10,,
cowidev.vax.batch.germany,0.12,True,2022-12-27T07:00:05,,
cowidev.vax.batch.greece,11.94,True,2022-12-27T07:00:17,,
cowidev.vax.batch.hong_kong,15.73,True,2022-12-27T07:00:20,,
cowidev.vax.batch.indonesia,,,2022-12-27T07:00:05,,
cowidev.vax.batch.ireland,4.47,True,2022-12-27T07:00:09,,
cowidev.vax.batch.israel,12.63,True,2022-12-27T07:00:17,,
cowidev.vax.batch.italy,5.49,True,2022-12-27T07:00:10,,
cowidev.vax.batch.japan,72.28,True,2022-12-27T07:01:17,,
cowidev.vax.batch.jersey,5.25,True,2022-12-27T07:00:10,,
cowidev.vax.batch.latvia,67.31,True,2022-12-27T07:01:12,,
cowidev.vax.batch.lithuania,5.6,True,2022-12-27T07:00:10,,
cowidev.vax.batch.luxembourg,16.82,True,2022-12-27T07:00:21,,
cowidev.vax.batch.malaysia,1.45,True,2022-12-27T07:00:06,,
cowidev.vax.batch.malta,1.87,True,2022-12-27T07:00:06,,
cowidev.vax.batch.netherlands,,,2022-12-27T07:00:05,,
cowidev.vax.batch.new_zealand,16.78,True,2022-12-27T07:00:21,,
cowidev.vax.batch.norway,1.71,True,2022-12-27T07:00:06,,
cowidev.vax.batch.peru,5.35,True,2022-12-27T07:00:10,,
cowidev.vax.batch.portugal,,,2022-12-27T07:00:05,,
cowidev.vax.batch.romania,52.79,True,2022-12-27T07:00:57,,
cowidev.vax.batch.saudi_arabia,7.33,True,2022-12-27T07:00:12,,
cowidev.vax.batch.singapore,5.01,True,2022-12-27T07:00:10,,
cowidev.vax.batch.slovakia,124.2,True,2022-12-27T07:02:09,,
cowidev.vax.batch.slovenia,3.27,True,2022-12-27T07:00:09,,
cowidev.vax.batch.south_korea,130.81,True,2022-12-27T07:02:17,,
cowidev.vax.batch.spc,22.16,True,2022-12-27T07:00:28,,
cowidev.vax.batch.sweden,28.52,True,2022-12-27T07:00:35,,
cowidev.vax.batch.switzerland,136.24,True,2022-12-27T07:02:25,,
cowidev.vax.batch.trinidad_and_tobago,7.02,True,2022-12-27T07:00:16,,
cowidev.vax.batch.ukraine,,,2022-12-27T07:00:10,,
cowidev.vax.batch.united_kingdom,12.1,True,2022-12-27T07:00:22,,
cowidev.vax.batch.united_states,137.48,True,2022-12-27T07:02:27,,
cowidev.vax.batch.uruguay,5.47,True,2022-12-27T07:00:15,,
cowidev.vax.batch.zimbabwe,1.56,True,2022-12-27T07:00:11,,
cowidev.vax.incremental.africacdc,,,2022-12-27T07:00:10,,
cowidev.vax.incremental.antigua_barbuda,,,2022-12-27T07:00:10,,
cowidev.vax.incremental.aruba,1.13,True,2022-12-27T07:00:11,,
cowidev.vax.incremental.azerbaijan,,,2022-12-27T07:00:10,,
cowidev.vax.incremental.bahrain,,,2022-12-27T07:00:10,,
cowidev.vax.incremental.bangladesh,33.58,True,2022-12-27T07:00:44,,
cowidev.vax.incremental.barbados,,,2022-12-27T07:00:10,,
cowidev.vax.incremental.brazil,1.02,True,2022-12-27T07:00:11,,
cowidev.vax.incremental.bulgaria,8.29,True,2022-12-27T07:00:19,,
cowidev.vax.incremental.china,32.01,True,2022-12-27T07:00:43,,
cowidev.vax.incremental.costa_rica,,,2022-12-27T07:00:11,,
cowidev.vax.incremental.croatia,0.82,True,2022-12-27T07:00:12,,
cowidev.vax.incremental.cuba,18.09,True,2022-12-27T07:00:30,,
cowidev.vax.incremental.curacao,0.96,True,2022-12-27T07:00:13,,
cowidev.vax.incremental.cyprus,7.45,True,2022-12-27T07:00:20,,
cowidev.vax.incremental.dominican_republic,12.89,True,2022-12-27T09:44:11,,
cowidev.vax.incremental.el_salvador,11.42,True,2022-12-27T07:00:27,,
cowidev.vax.incremental.faeroe_islands,1.19,True,2022-12-27T07:00:17,,
cowidev.vax.incremental.fiji,0.0,True,2022-12-27T07:00:16,,
cowidev.vax.incremental.finland,0.6,True,2022-12-27T07:00:17,,
cowidev.vax.incremental.gabon,,,2022-12-27T07:00:16,,
cowidev.vax.incremental.georgia,6.34,True,2022-12-27T07:00:23,,
cowidev.vax.incremental.greenland,2.2,True,2022-12-27T07:00:19,,
cowidev.vax.incremental.guatemala,,,2022-12-27T07:00:17,,
cowidev.vax.incremental.guernsey,9.66,True,2022-12-27T07:00:26,,
cowidev.vax.incremental.hungary,5.86,True,2022-12-27T07:00:23,,
cowidev.vax.incremental.iceland,3.16,True,2022-12-27T07:00:20,,
cowidev.vax.incremental.india,3.03,True,2022-12-27T07:00:20,,
cowidev.vax.incremental.iran,,,2022-12-27T07:00:19,,
cowidev.vax.incremental.isle_of_man,2.15,True,2022-12-27T07:00:21,,
cowidev.vax.incremental.jamaica,10.97,True,2022-12-27T07:00:30,,
cowidev.vax.incremental.kazakhstan,7.52,True,2022-12-27T07:00:27,,
cowidev.vax.incremental.kosovo,5.31,False,2022-12-27T09:51:59,"Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 82, in main
    Kosovo().export()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 23, in read
    df = self._parse_data(soup)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 32, in _parse_data
    soup = get_soup(link, verify=False)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
",Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
cowidev.vax.incremental.kyrgyzstan,5.99,True,2022-12-27T07:00:26,,
cowidev.vax.incremental.laos,10.21,True,2022-12-27T07:00:31,,
cowidev.vax.incremental.macao,12.05,True,2022-12-27T07:00:33,,
cowidev.vax.incremental.moldova,,,2022-12-27T07:00:21,,
cowidev.vax.incremental.monaco,128.75,True,2022-12-27T07:02:30,,
cowidev.vax.incremental.mongolia,1.96,True,2022-12-27T07:00:23,,
cowidev.vax.incremental.montenegro,1.0,True,2022-12-27T07:00:23,,
cowidev.vax.incremental.morocco,,,2022-12-27T07:00:23,,
cowidev.vax.incremental.myanmar,,,2022-12-27T07:00:23,,
cowidev.vax.incremental.nepal,,,2022-12-27T07:00:23,,
cowidev.vax.incremental.north_macedonia,,,2022-12-27T07:00:23,,
cowidev.vax.incremental.northern_cyprus,6.71,True,2022-12-27T07:00:29,,
cowidev.vax.incremental.paho,76.23,True,2022-12-27T09:45:15,,
cowidev.vax.incremental.pakistan,1.07,False,2022-12-27T09:45:21,"Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1040, in _validate_conn
    conn.connect()
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 416, in connect
    self.sock = ssl_wrap_socket(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py"", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py"", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File ""/usr/lib/python3.10/ssl.py"", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File ""/usr/lib/python3.10/ssl.py"", line 1071, in _create
    self.do_handshake()
  File ""/usr/lib/python3.10/ssl.py"", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 785, in urlopen
    retries = retries.increment(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid.gov.pk', port=443): Max retries exceeded with url: /vaccine-details (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/pakistan.py"", line 58, in main
    Pakistan().export()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/pakistan.py"", line 53, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/pakistan.py"", line 17, in read
    soup = get_soup(self.source_url)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/adapters.py"", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='covid.gov.pk', port=443): Max retries exceeded with url: /vaccine-details (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
","HTTPSConnectionPool(host='covid.gov.pk', port=443): Max retries exceeded with url: /vaccine-details (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))"
cowidev.vax.incremental.philippines,,,2022-12-27T07:00:23,,
cowidev.vax.incremental.poland,2.34,True,2022-12-27T07:00:26,,
cowidev.vax.incremental.qatar,,,2022-12-27T07:00:25,,
cowidev.vax.incremental.russia,59.17,True,2022-12-27T07:01:24,,
cowidev.vax.incremental.saint_lucia,,,2022-12-27T07:00:26,,
cowidev.vax.incremental.serbia,0.55,False,2022-12-27T09:51:09,"Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 88, in main
    Serbia().export()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 74, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 23, in read
    soup = get_soup(self.source_url)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://vakcinacija.gov.rs/ not reached! Error code 503 Service Unavailable
",Source https://vakcinacija.gov.rs/ not reached! Error code 503 Service Unavailable
cowidev.vax.incremental.south_africa,0.65,False,2022-12-27T09:45:20,"Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/south_africa.py"", line 274, in main
    SouthAfrica().export()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/south_africa.py"", line 256, in export
    df_main, df_manufacturer = self.read()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/south_africa.py"", line 150, in read
    df_main, df_manufacturer = self._parse_data()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/south_africa.py"", line 161, in _parse_data
    Pfizer_first = response[""results""][0][""result""][""data""][""dsr""][""DS""][0][""PH""][0][""DM0""][0][""M0""]
KeyError: 'DS'
",'DS'
cowidev.vax.incremental.spain,37.03,True,2022-12-27T07:01:03,,
cowidev.vax.incremental.sri_lanka,,,2022-12-27T07:00:27,,
cowidev.vax.incremental.suriname,15.42,True,2022-12-27T07:00:42,,
cowidev.vax.incremental.taiwan,26.38,True,2022-12-27T07:00:53,,
cowidev.vax.incremental.thailand,9.06,True,2022-12-27T07:00:36,,
cowidev.vax.incremental.turkey,41.97,False,2022-12-27T09:46:03,"Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1040, in _validate_conn
    conn.connect()
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fc7347a6680>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 785, in urlopen
    retries = retries.increment(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7347a6680>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7347a6680>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7347a6680>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2022-12-27T07:00:29,,
cowidev.vax.incremental.vietnam,,,2022-12-27T07:00:29,,
cowidev.vax.incremental.who,1.59,True,2022-12-27T09:51:20,,
cowidev.vax.incremental.zambia,2.42,True,2022-12-27T07:00:32,,
