module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,17.03,True,2023-01-02T07:00:23,,
cowidev.vax.batch.australia,130.45,True,2023-01-02T07:02:16,,
cowidev.vax.batch.austria,17.06,True,2023-01-02T07:00:23,,
cowidev.vax.batch.belgium,12.87,True,2023-01-02T07:00:19,,
cowidev.vax.batch.bolivia,5.0,True,2023-01-02T07:00:11,,
cowidev.vax.batch.canada,30.94,True,2023-01-02T07:00:37,,
cowidev.vax.batch.chile,0.88,True,2023-01-02T07:00:07,,
cowidev.vax.batch.czechia,38.59,True,2023-01-02T07:00:44,,
cowidev.vax.batch.denmark,133.52,True,2023-01-02T07:02:19,,
cowidev.vax.batch.ecdc,140.27,True,2023-01-02T07:02:26,,
cowidev.vax.batch.ecuador,,,2023-01-02T07:00:06,,
cowidev.vax.batch.estonia,0.65,True,2023-01-02T07:00:06,,
cowidev.vax.batch.france,7.09,True,2023-01-02T07:00:13,,
cowidev.vax.batch.germany,0.16,True,2023-01-02T07:00:06,,
cowidev.vax.batch.greece,20.09,True,2023-01-02T07:00:26,,
cowidev.vax.batch.hong_kong,22.08,True,2023-01-02T07:00:28,,
cowidev.vax.batch.indonesia,,,2023-01-02T07:00:06,,
cowidev.vax.batch.ireland,5.1,True,2023-01-02T07:00:11,,
cowidev.vax.batch.israel,15.45,True,2023-01-02T07:00:21,,
cowidev.vax.batch.italy,7.55,True,2023-01-02T07:00:13,,
cowidev.vax.batch.japan,56.39,True,2023-01-02T07:01:02,,
cowidev.vax.batch.jersey,5.74,True,2023-01-02T07:00:11,,
cowidev.vax.batch.latvia,71.06,True,2023-01-02T07:01:17,,
cowidev.vax.batch.lithuania,5.74,True,2023-01-02T07:00:11,,
cowidev.vax.batch.luxembourg,3.44,True,2023-01-02T07:00:09,,
cowidev.vax.batch.malaysia,0.8,True,2023-01-02T07:00:06,,
cowidev.vax.batch.malta,1.36,True,2023-01-02T07:00:07,,
cowidev.vax.batch.netherlands,,,2023-01-02T07:00:06,,
cowidev.vax.batch.new_zealand,15.38,True,2023-01-02T07:00:21,,
cowidev.vax.batch.norway,0.51,True,2023-01-02T07:00:06,,
cowidev.vax.batch.peru,5.24,True,2023-01-02T07:00:11,,
cowidev.vax.batch.portugal,,,2023-01-02T07:00:06,,
cowidev.vax.batch.romania,50.61,True,2023-01-02T07:00:56,,
cowidev.vax.batch.saudi_arabia,8.59,True,2023-01-02T07:00:14,,
cowidev.vax.batch.singapore,5.42,True,2023-01-02T07:00:11,,
cowidev.vax.batch.slovakia,116.41,True,2023-01-02T07:02:02,,
cowidev.vax.batch.slovenia,3.33,True,2023-01-02T07:00:10,,
cowidev.vax.batch.south_korea,124.92,True,2023-01-02T07:02:11,,
cowidev.vax.batch.spc,25.75,True,2023-01-02T07:00:32,,
cowidev.vax.batch.sweden,20.25,True,2023-01-02T07:00:27,,
cowidev.vax.batch.switzerland,135.53,True,2023-01-02T07:02:23,,
cowidev.vax.batch.trinidad_and_tobago,3.2,True,2023-01-02T07:00:12,,
cowidev.vax.batch.ukraine,,,2023-01-02T07:00:10,,
cowidev.vax.batch.united_kingdom,18.65,True,2023-01-02T07:00:28,,
cowidev.vax.batch.united_states,135.79,True,2023-01-02T07:02:26,,
cowidev.vax.batch.uruguay,9.08,True,2023-01-02T07:00:20,,
cowidev.vax.batch.zimbabwe,2.15,True,2023-01-02T07:00:13,,
cowidev.vax.incremental.africacdc,,,2023-01-02T07:00:11,,
cowidev.vax.incremental.antigua_barbuda,,,2023-01-02T07:00:11,,
cowidev.vax.incremental.aruba,1.37,True,2023-01-02T07:00:12,,
cowidev.vax.incremental.azerbaijan,,,2023-01-02T07:00:11,,
cowidev.vax.incremental.bahrain,,,2023-01-02T07:00:11,,
cowidev.vax.incremental.bangladesh,38.45,True,2023-01-02T07:00:50,,
cowidev.vax.incremental.barbados,,,2023-01-02T07:00:11,,
cowidev.vax.incremental.brazil,0.84,True,2023-01-02T07:00:12,,
cowidev.vax.incremental.bulgaria,13.62,True,2023-01-02T07:00:26,,
cowidev.vax.incremental.china,30.29,True,2023-01-02T07:00:43,,
cowidev.vax.incremental.costa_rica,,,2023-01-02T07:00:12,,
cowidev.vax.incremental.croatia,1.29,True,2023-01-02T07:00:14,,
cowidev.vax.incremental.cuba,3.38,False,2023-01-02T07:03:58,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/cuba.py"", line 81, in main
    Cuba().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/cuba.py"", line 67, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/cuba.py"", line 28, in read
    return self._parse_data(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/cuba.py"", line 33, in _parse_data
    ""date"": self._parse_date(soup),
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/cuba.py"", line 43, in _parse_date
    date = clean_date(f""{date_str} {datetime.now().year-1}"", ""%d de %b %Y"", lang=""es"")
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/clean/dates.py"", line 76, in clean_date
    dt = datetime.strptime(date_or_text, fmt) - timedelta(days=minus_days)
  File ""/usr/lib/python3.10/_strptime.py"", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File ""/usr/lib/python3.10/_strptime.py"", line 349, in _strptime
    raise ValueError(""time data %r does not match format %r"" %
ValueError: time data '29 de diciembre 2022' does not match format '%d de %b %Y'
",time data '29 de diciembre 2022' does not match format '%d de %b %Y'
cowidev.vax.incremental.curacao,1.22,True,2023-01-02T07:00:14,,
cowidev.vax.incremental.cyprus,4.29,True,2023-01-02T07:00:18,,
cowidev.vax.incremental.dominican_republic,22.77,False,2023-01-02T07:04:21,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 113, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 92, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 82, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,15.09,True,2023-01-02T07:00:29,,
cowidev.vax.incremental.faeroe_islands,2.38,True,2023-01-02T07:00:17,,
cowidev.vax.incremental.fiji,0.0,True,2023-01-02T07:00:17,,
cowidev.vax.incremental.finland,1.13,True,2023-01-02T07:00:18,,
cowidev.vax.incremental.gabon,,,2023-01-02T07:00:18,,
cowidev.vax.incremental.georgia,9.36,True,2023-01-02T07:00:27,,
cowidev.vax.incremental.greenland,5.0,True,2023-01-02T07:00:23,,
cowidev.vax.incremental.guatemala,,,2023-01-02T07:00:19,,
cowidev.vax.incremental.guernsey,10.5,True,2023-01-02T07:00:29,,
cowidev.vax.incremental.hungary,6.63,True,2023-01-02T07:00:27,,
cowidev.vax.incremental.iceland,5.3,True,2023-01-02T07:00:26,,
cowidev.vax.incremental.india,3.52,True,2023-01-02T07:00:25,,
cowidev.vax.incremental.iran,,,2023-01-02T07:00:23,,
cowidev.vax.incremental.isle_of_man,2.74,True,2023-01-02T07:00:25,,
cowidev.vax.incremental.jamaica,8.16,True,2023-01-02T07:00:31,,
cowidev.vax.incremental.kazakhstan,8.16,True,2023-01-02T07:00:31,,
cowidev.vax.incremental.kosovo,6.68,True,2023-01-02T07:00:31,,
cowidev.vax.incremental.kyrgyzstan,4.7,True,2023-01-02T07:00:30,,
cowidev.vax.incremental.laos,7.75,True,2023-01-02T07:00:34,,
cowidev.vax.incremental.macao,12.86,True,2023-01-02T07:00:39,,
cowidev.vax.incremental.moldova,,,2023-01-02T07:00:26,,
cowidev.vax.incremental.monaco,123.68,True,2023-01-02T07:02:30,,
cowidev.vax.incremental.mongolia,1.14,True,2023-01-02T07:00:28,,
cowidev.vax.incremental.montenegro,0.91,True,2023-01-02T07:00:28,,
cowidev.vax.incremental.morocco,,,2023-01-02T07:00:27,,
cowidev.vax.incremental.myanmar,,,2023-01-02T07:00:27,,
cowidev.vax.incremental.nepal,,,2023-01-02T07:00:27,,
cowidev.vax.incremental.north_macedonia,,,2023-01-02T07:00:27,,
cowidev.vax.incremental.northern_cyprus,4.87,True,2023-01-02T07:00:32,,
cowidev.vax.incremental.paho,137.34,False,2023-01-02T07:06:38,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 64, in _parse_data
    filename = self._get_downloaded_filename()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 116, in _get_downloaded_filename
    return max(files, key=os.path.getctime)
ValueError: max() arg is an empty sequence
",max() arg is an empty sequence
cowidev.vax.incremental.pakistan,,,2023-01-02T07:00:28,,
cowidev.vax.incremental.philippines,,,2023-01-02T07:00:28,,
cowidev.vax.incremental.poland,1.34,True,2023-01-02T07:00:29,,
cowidev.vax.incremental.qatar,,,2023-01-02T07:00:28,,
cowidev.vax.incremental.russia,59.84,True,2023-01-02T07:01:28,,
cowidev.vax.incremental.saint_lucia,,,2023-01-02T07:00:28,,
cowidev.vax.incremental.serbia,0.36,False,2023-01-02T07:06:38,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 88, in main
    Serbia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 74, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/serbia.py"", line 23, in read
    soup = get_soup(self.source_url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://vakcinacija.gov.rs/ not reached! Error code 503 Service Unavailable
",Source https://vakcinacija.gov.rs/ not reached! Error code 503 Service Unavailable
cowidev.vax.incremental.south_africa,,,2023-01-02T07:00:29,,
cowidev.vax.incremental.spain,27.13,True,2023-01-02T07:00:56,,
cowidev.vax.incremental.sri_lanka,,,2023-01-02T07:00:29,,
cowidev.vax.incremental.suriname,15.15,True,2023-01-02T07:00:44,,
cowidev.vax.incremental.taiwan,24.12,True,2023-01-02T07:00:53,,
cowidev.vax.incremental.thailand,6.54,True,2023-01-02T07:00:36,,
cowidev.vax.incremental.turkey,40.05,False,2023-01-02T07:07:18,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1042, in _validate_conn
    conn.connect()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    self.sock = conn = self._new_conn()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f5cf16d61d0>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5cf16d61d0>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5cf16d61d0>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5cf16d61d0>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2023-01-02T07:00:31,,
cowidev.vax.incremental.vietnam,,,2023-01-02T07:00:31,,
cowidev.vax.incremental.who,70.36,True,2023-01-02T07:01:41,,
cowidev.vax.incremental.zambia,1.34,True,2023-01-02T07:00:32,,
