module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,13.97,True,2022-11-27T07:00:19,,
cowidev.vax.batch.australia,40.64,False,2022-11-27T07:03:51,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 449, in _make_request
    six.raise_from(e, None)
  File ""<string>"", line 3, in raise_from
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 444, in _make_request
    httplib_response = conn.getresponse()
  File ""/usr/lib/python3.10/http/client.py"", line 1374, in getresponse
    response.begin()
  File ""/usr/lib/python3.10/http/client.py"", line 318, in begin
    version, status, reason = self._read_status()
  File ""/usr/lib/python3.10/http/client.py"", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), ""iso-8859-1"")
  File ""/usr/lib/python3.10/socket.py"", line 705, in readinto
    return self._sock.recv_into(b)
  File ""/usr/lib/python3.10/ssl.py"", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File ""/usr/lib/python3.10/ssl.py"", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/packages/six.py"", line 770, in reraise
    raise value
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.health.gov.au', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 227, in main
    Australia().export_official()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 211, in export_official
    df = self.pipeline_latest_from_official_source(self.read_latest_from_official_source())  # Use with attach=True
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 74, in read_latest_from_official_source
    soup = get_soup(url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.health.gov.au', port=443): Read timed out. (read timeout=20)
","HTTPSConnectionPool(host='www.health.gov.au', port=443): Read timed out. (read timeout=20)"
cowidev.vax.batch.austria,13.21,True,2022-11-27T07:00:18,,
cowidev.vax.batch.belgium,6.5,True,2022-11-27T07:00:12,,
cowidev.vax.batch.bolivia,3.93,True,2022-11-27T07:00:09,,
cowidev.vax.batch.canada,19.08,True,2022-11-27T07:00:24,,
cowidev.vax.batch.chile,1.24,True,2022-11-27T07:00:07,,
cowidev.vax.batch.czechia,2.82,True,2022-11-27T07:00:08,,
cowidev.vax.batch.denmark,75.3,True,2022-11-27T07:01:21,,
cowidev.vax.batch.ecdc,83.71,True,2022-11-27T07:01:29,,
cowidev.vax.batch.ecuador,2.47,True,2022-11-27T07:00:08,,
cowidev.vax.batch.estonia,0.73,True,2022-11-27T07:00:06,,
cowidev.vax.batch.france,6.46,True,2022-11-27T07:00:12,,
cowidev.vax.batch.germany,4.16,True,2022-11-27T07:00:09,,
cowidev.vax.batch.greece,14.48,True,2022-11-27T07:00:20,,
cowidev.vax.batch.hong_kong,17.05,True,2022-11-27T07:00:22,,
cowidev.vax.batch.indonesia,,,2022-11-27T07:00:05,,
cowidev.vax.batch.ireland,4.25,True,2022-11-27T07:00:10,,
cowidev.vax.batch.israel,12.89,True,2022-11-27T07:00:18,,
cowidev.vax.batch.italy,7.94,True,2022-11-27T07:00:13,,
cowidev.vax.batch.japan,37.08,True,2022-11-27T07:00:42,,
cowidev.vax.batch.jersey,6.07,True,2022-11-27T07:00:11,,
cowidev.vax.batch.latvia,53.67,True,2022-11-27T07:00:59,,
cowidev.vax.batch.lithuania,7.5,True,2022-11-27T07:00:13,,
cowidev.vax.batch.luxembourg,3.85,True,2022-11-27T07:00:09,,
cowidev.vax.batch.malaysia,0.8,True,2022-11-27T07:00:06,,
cowidev.vax.batch.malta,1.15,True,2022-11-27T07:00:06,,
cowidev.vax.batch.netherlands,,,2022-11-27T07:00:05,,
cowidev.vax.batch.new_zealand,13.49,True,2022-11-27T07:00:19,,
cowidev.vax.batch.norway,0.38,True,2022-11-27T07:00:06,,
cowidev.vax.batch.peru,4.93,True,2022-11-27T07:00:10,,
cowidev.vax.batch.portugal,,,2022-11-27T07:00:05,,
cowidev.vax.batch.romania,31.54,True,2022-11-27T07:00:37,,
cowidev.vax.batch.saudi_arabia,9.09,True,2022-11-27T07:00:14,,
cowidev.vax.batch.singapore,5.74,True,2022-11-27T07:00:11,,
cowidev.vax.batch.slovakia,61.85,True,2022-11-27T07:01:08,,
cowidev.vax.batch.slovenia,3.45,True,2022-11-27T07:00:10,,
cowidev.vax.batch.south_korea,93.21,True,2022-11-27T07:01:40,,
cowidev.vax.batch.spc,17.97,True,2022-11-27T07:00:25,,
cowidev.vax.batch.sweden,15.21,True,2022-11-27T07:00:23,,
cowidev.vax.batch.switzerland,73.46,True,2022-11-27T07:01:22,,
cowidev.vax.batch.trinidad_and_tobago,3.73,True,2022-11-27T07:00:13,,
cowidev.vax.batch.ukraine,,,2022-11-27T07:00:09,,
cowidev.vax.batch.united_kingdom,13.36,True,2022-11-27T07:00:23,,
cowidev.vax.batch.united_states,80.27,True,2022-11-27T07:01:30,,
cowidev.vax.batch.uruguay,5.63,True,2022-11-27T07:00:15,,
cowidev.vax.batch.zimbabwe,2.1,True,2022-11-27T07:00:12,,
cowidev.vax.incremental.africacdc,,,2022-11-27T07:00:10,,
cowidev.vax.incremental.antigua_barbuda,,,2022-11-27T07:00:10,,
cowidev.vax.incremental.aruba,1.19,True,2022-11-27T07:00:11,,
cowidev.vax.incremental.azerbaijan,,,2022-11-27T07:00:11,,
cowidev.vax.incremental.bahrain,4.77,True,2022-11-27T07:00:16,,
cowidev.vax.incremental.bangladesh,33.06,True,2022-11-27T07:00:44,,
cowidev.vax.incremental.barbados,,,2022-11-27T07:00:11,,
cowidev.vax.incremental.brazil,0.65,True,2022-11-27T07:00:12,,
cowidev.vax.incremental.bulgaria,8.04,True,2022-11-27T07:00:20,,
cowidev.vax.incremental.china,25.64,True,2022-11-27T07:00:37,,
cowidev.vax.incremental.costa_rica,,,2022-11-27T07:00:12,,
cowidev.vax.incremental.croatia,0.73,True,2022-11-27T07:00:13,,
cowidev.vax.incremental.cuba,10.87,True,2022-11-27T07:00:23,,
cowidev.vax.incremental.curacao,0.81,True,2022-11-27T07:00:13,,
cowidev.vax.incremental.cyprus,2.46,True,2022-11-27T07:00:15,,
cowidev.vax.incremental.dominican_republic,22.55,False,2022-11-27T07:04:13,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 113, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 92, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 82, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,10.26,True,2022-11-27T07:00:23,,
cowidev.vax.incremental.faeroe_islands,2.12,True,2022-11-27T07:00:15,,
cowidev.vax.incremental.fiji,0.0,True,2022-11-27T07:00:14,,
cowidev.vax.incremental.finland,0.41,True,2022-11-27T07:00:15,,
cowidev.vax.incremental.gabon,,,2022-11-27T07:00:15,,
cowidev.vax.incremental.georgia,7.53,True,2022-11-27T07:00:22,,
cowidev.vax.incremental.greenland,3.98,True,2022-11-27T07:00:19,,
cowidev.vax.incremental.guatemala,,,2022-11-27T07:00:15,,
cowidev.vax.incremental.guernsey,5.95,True,2022-11-27T07:00:21,,
cowidev.vax.incremental.hungary,5.44,True,2022-11-27T07:00:21,,
cowidev.vax.incremental.iceland,3.97,True,2022-11-27T07:00:20,,
cowidev.vax.incremental.india,2.56,True,2022-11-27T07:00:21,,
cowidev.vax.incremental.iran,,,2022-11-27T07:00:18,,
cowidev.vax.incremental.isle_of_man,1.94,True,2022-11-27T07:00:20,,
cowidev.vax.incremental.jamaica,5.25,True,2022-11-27T07:00:24,,
cowidev.vax.incremental.kazakhstan,10.29,True,2022-11-27T07:00:29,,
cowidev.vax.incremental.kosovo,4.43,True,2022-11-27T07:00:24,,
cowidev.vax.incremental.kyrgyzstan,3.14,True,2022-11-27T07:00:23,,
cowidev.vax.incremental.laos,4.38,True,2022-11-27T07:00:24,,
cowidev.vax.incremental.macao,12.14,True,2022-11-27T07:00:32,,
cowidev.vax.incremental.moldova,,,2022-11-27T07:00:20,,
cowidev.vax.incremental.monaco,81.71,True,2022-11-27T07:01:42,,
cowidev.vax.incremental.mongolia,1.06,True,2022-11-27T07:00:22,,
cowidev.vax.incremental.montenegro,0.78,True,2022-11-27T07:00:22,,
cowidev.vax.incremental.morocco,,,2022-11-27T07:00:21,,
cowidev.vax.incremental.myanmar,,,2022-11-27T07:00:21,,
cowidev.vax.incremental.nepal,,,2022-11-27T07:00:21,,
cowidev.vax.incremental.north_macedonia,,,2022-11-27T07:00:21,,
cowidev.vax.incremental.northern_cyprus,2.77,True,2022-11-27T07:00:24,,
cowidev.vax.incremental.paho,136.6,False,2022-11-27T07:06:30,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 185, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 57, in _parse_data
    filename = self._get_downloaded_filename()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 109, in _get_downloaded_filename
    return max(files, key=os.path.getctime)
ValueError: max() arg is an empty sequence
",max() arg is an empty sequence
cowidev.vax.incremental.pakistan,2.53,True,2022-11-27T07:00:24,,
cowidev.vax.incremental.philippines,,,2022-11-27T07:00:22,,
cowidev.vax.incremental.playground_mojmir,4.01,True,2022-11-27T07:00:26,,
cowidev.vax.incremental.poland,0.91,True,2022-11-27T07:00:23,,
cowidev.vax.incremental.qatar,,,2022-11-27T07:00:23,,
cowidev.vax.incremental.russia,45.28,True,2022-11-27T07:01:08,,
cowidev.vax.incremental.saint_lucia,,,2022-11-27T07:00:23,,
cowidev.vax.incremental.serbia,10.45,True,2022-11-27T07:00:33,,
cowidev.vax.incremental.south_africa,9.39,True,2022-11-27T07:00:32,,
cowidev.vax.incremental.spain,32.59,True,2022-11-27T07:00:56,,
cowidev.vax.incremental.sri_lanka,,,2022-11-27T07:00:23,,
cowidev.vax.incremental.suriname,14.69,True,2022-11-27T07:00:38,,
cowidev.vax.incremental.taiwan,18.77,True,2022-11-27T07:00:42,,
cowidev.vax.incremental.thailand,6.93,True,2022-11-27T07:00:31,,
cowidev.vax.incremental.turkey,40.04,False,2022-11-27T07:07:10,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1042, in _validate_conn
    conn.connect()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    self.sock = conn = self._new_conn()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f767acc5f60>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f767acc5f60>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f767acc5f60>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f767acc5f60>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2022-11-27T07:00:24,,
cowidev.vax.incremental.vietnam,,,2022-11-27T07:00:24,,
cowidev.vax.incremental.who,44.02,True,2022-11-27T07:01:08,,
cowidev.vax.incremental.zambia,1.82,True,2022-11-27T07:00:26,,
