module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,15.62,True,2023-01-25T07:00:21,,
cowidev.vax.batch.australia,116.38,True,2023-01-25T07:02:02,,
cowidev.vax.batch.austria,12.56,True,2023-01-25T07:00:18,,
cowidev.vax.batch.belgium,14.85,True,2023-01-25T07:00:20,,
cowidev.vax.batch.bolivia,4.79,True,2023-01-25T07:00:10,,
cowidev.vax.batch.canada,27.47,True,2023-01-25T07:00:33,,
cowidev.vax.batch.chile,1.06,True,2023-01-25T07:00:07,,
cowidev.vax.batch.czechia,38.3,True,2023-01-25T07:00:44,,
cowidev.vax.batch.denmark,115.24,True,2023-01-25T07:02:01,,
cowidev.vax.batch.ecdc,120.43,True,2023-01-25T07:02:06,,
cowidev.vax.batch.ecuador,,,2023-01-25T07:00:06,,
cowidev.vax.batch.estonia,0.66,True,2023-01-25T07:00:06,,
cowidev.vax.batch.france,6.96,True,2023-01-25T07:00:13,,
cowidev.vax.batch.germany,0.16,True,2023-01-25T07:00:06,,
cowidev.vax.batch.greece,19.45,True,2023-01-25T07:00:25,,
cowidev.vax.batch.hong_kong,18.81,True,2023-01-25T07:00:24,,
cowidev.vax.batch.indonesia,,,2023-01-25T07:00:06,,
cowidev.vax.batch.ireland,3.81,True,2023-01-25T07:00:09,,
cowidev.vax.batch.israel,9.59,True,2023-01-25T07:00:15,,
cowidev.vax.batch.italy,8.0,True,2023-01-25T07:00:14,,
cowidev.vax.batch.japan,49.49,True,2023-01-25T07:00:55,,
cowidev.vax.batch.jersey,3.93,True,2023-01-25T07:00:10,,
cowidev.vax.batch.latvia,66.74,True,2023-01-25T07:01:12,,
cowidev.vax.batch.lithuania,5.23,True,2023-01-25T07:00:11,,
cowidev.vax.batch.luxembourg,2.69,True,2023-01-25T07:00:08,,
cowidev.vax.batch.malaysia,0.81,True,2023-01-25T07:00:06,,
cowidev.vax.batch.malta,1.64,True,2023-01-25T07:00:07,,
cowidev.vax.batch.netherlands,,,2023-01-25T07:00:06,,
cowidev.vax.batch.new_zealand,14.91,True,2023-01-25T07:00:21,,
cowidev.vax.batch.norway,0.66,True,2023-01-25T07:00:06,,
cowidev.vax.batch.peru,6.47,True,2023-01-25T07:00:12,,
cowidev.vax.batch.portugal,,,2023-01-25T07:00:06,,
cowidev.vax.batch.romania,106.21,True,2023-01-25T07:01:52,,
cowidev.vax.batch.saudi_arabia,10.53,True,2023-01-25T07:00:16,,
cowidev.vax.batch.singapore,4.73,True,2023-01-25T07:00:10,,
cowidev.vax.batch.slovakia,85.15,True,2023-01-25T07:01:31,,
cowidev.vax.batch.slovenia,2.85,True,2023-01-25T07:00:09,,
cowidev.vax.batch.south_korea,117.66,True,2023-01-25T07:02:04,,
cowidev.vax.batch.spc,28.31,True,2023-01-25T07:00:35,,
cowidev.vax.batch.sweden,17.43,True,2023-01-25T07:00:24,,
cowidev.vax.batch.switzerland,164.31,True,2023-01-25T07:02:52,,
cowidev.vax.batch.trinidad_and_tobago,3.26,True,2023-01-25T07:00:12,,
cowidev.vax.batch.ukraine,,,2023-01-25T07:00:09,,
cowidev.vax.batch.united_kingdom,16.71,True,2023-01-25T07:00:26,,
cowidev.vax.batch.united_states,117.32,True,2023-01-25T07:02:07,,
cowidev.vax.batch.uruguay,7.42,True,2023-01-25T07:00:17,,
cowidev.vax.batch.zimbabwe,2.58,True,2023-01-25T07:00:13,,
cowidev.vax.incremental.africacdc,,,2023-01-25T07:00:10,,
cowidev.vax.incremental.antigua_barbuda,,,2023-01-25T07:00:10,,
cowidev.vax.incremental.aruba,2.3,True,2023-01-25T07:00:13,,
cowidev.vax.incremental.azerbaijan,,,2023-01-25T07:00:11,,
cowidev.vax.incremental.bahrain,,,2023-01-25T07:00:11,,
cowidev.vax.incremental.bangladesh,39.57,True,2023-01-25T07:00:50,,
cowidev.vax.incremental.barbados,,,2023-01-25T07:00:12,,
cowidev.vax.incremental.brazil,1.74,True,2023-01-25T07:00:13,,
cowidev.vax.incremental.bulgaria,11.32,True,2023-01-25T07:00:23,,
cowidev.vax.incremental.china,17.62,True,2023-01-25T07:00:30,,
cowidev.vax.incremental.costa_rica,,,2023-01-25T07:00:13,,
cowidev.vax.incremental.croatia,0.6,True,2023-01-25T07:00:13,,
cowidev.vax.incremental.cuba,16.94,True,2023-01-25T07:00:30,,
cowidev.vax.incremental.curacao,1.02,True,2023-01-25T07:00:14,,
cowidev.vax.incremental.cyprus,3.11,True,2023-01-25T07:00:16,,
cowidev.vax.incremental.dominican_republic,22.6,False,2023-01-25T07:03:57,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 113, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 92, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 82, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,13.15,True,2023-01-25T07:00:27,,
cowidev.vax.incremental.faeroe_islands,1.52,True,2023-01-25T07:00:17,,
cowidev.vax.incremental.fiji,0.0,True,2023-01-25T07:00:16,,
cowidev.vax.incremental.finland,0.91,True,2023-01-25T07:00:17,,
cowidev.vax.incremental.gabon,,,2023-01-25T07:00:16,,
cowidev.vax.incremental.georgia,9.78,True,2023-01-25T07:00:26,,
cowidev.vax.incremental.greenland,1.33,False,2023-01-25T07:03:58,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 76, in main
    Greenland().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 63, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 17, in read
    data = self._parse_data(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 21, in _parse_data
    return {**self._parse_data_metrics(soup), **self._parse_data_date(soup)}
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 31, in _parse_data_metrics
    assert len(counter_1) == len(counter_2) == 1
AssertionError
",
cowidev.vax.incremental.guatemala,,,2023-01-25T07:00:17,,
cowidev.vax.incremental.guernsey,12.53,True,2023-01-25T07:00:29,,
cowidev.vax.incremental.hungary,108.62,True,2023-01-25T07:02:06,,
cowidev.vax.incremental.iceland,4.83,True,2023-01-25T07:00:23,,
cowidev.vax.incremental.india,3.49,True,2023-01-25T07:00:24,,
cowidev.vax.incremental.iran,,,2023-01-25T07:00:21,,
cowidev.vax.incremental.isle_of_man,1.99,True,2023-01-25T07:00:22,,
cowidev.vax.incremental.jamaica,9.36,True,2023-01-25T07:00:31,,
cowidev.vax.incremental.kazakhstan,6.93,True,2023-01-25T07:00:29,,
cowidev.vax.incremental.kosovo,8.09,False,2023-01-25T07:04:06,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 82, in main
    Kosovo().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 23, in read
    df = self._parse_data(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 32, in _parse_data
    soup = get_soup(link, verify=False)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
",Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
cowidev.vax.incremental.kyrgyzstan,4.92,True,2023-01-25T07:00:28,,
cowidev.vax.incremental.laos,6.61,True,2023-01-25T07:00:31,,
cowidev.vax.incremental.macao,11.57,True,2023-01-25T07:00:36,,
cowidev.vax.incremental.moldova,,,2023-01-25T07:00:24,,
cowidev.vax.incremental.monaco,114.21,True,2023-01-25T07:02:19,,
cowidev.vax.incremental.mongolia,1.13,True,2023-01-25T07:00:26,,
cowidev.vax.incremental.montenegro,0.87,True,2023-01-25T07:00:26,,
cowidev.vax.incremental.morocco,,,2023-01-25T07:00:26,,
cowidev.vax.incremental.myanmar,,,2023-01-25T07:00:26,,
cowidev.vax.incremental.nepal,,,2023-01-25T07:00:26,,
cowidev.vax.incremental.north_macedonia,,,2023-01-25T07:00:26,,
cowidev.vax.incremental.northern_cyprus,4.83,True,2023-01-25T07:00:31,,
cowidev.vax.incremental.paho,136.73,False,2023-01-25T07:06:23,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 37, in read
    df = self._parse_data(url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 64, in _parse_data
    filename = self._get_downloaded_filename()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 116, in _get_downloaded_filename
    return max(files, key=os.path.getctime)
ValueError: max() arg is an empty sequence
",max() arg is an empty sequence
cowidev.vax.incremental.pakistan,,,2023-01-25T07:00:26,,
cowidev.vax.incremental.philippines,,,2023-01-25T07:00:26,,
cowidev.vax.incremental.poland,1.78,True,2023-01-25T07:00:28,,
cowidev.vax.incremental.qatar,,,2023-01-25T07:00:26,,
cowidev.vax.incremental.russia,23.74,True,2023-01-25T07:00:50,,
cowidev.vax.incremental.saint_lucia,,,2023-01-25T07:00:27,,
cowidev.vax.incremental.serbia,13.0,True,2023-01-25T07:00:40,,
cowidev.vax.incremental.south_africa,,,2023-01-25T07:00:28,,
cowidev.vax.incremental.spain,12.97,True,2023-01-25T07:00:41,,
cowidev.vax.incremental.sri_lanka,,,2023-01-25T07:00:28,,
cowidev.vax.incremental.suriname,15.35,True,2023-01-25T07:00:44,,
cowidev.vax.incremental.taiwan,19.45,True,2023-01-25T07:00:49,,
cowidev.vax.incremental.thailand,8.34,True,2023-01-25T07:00:38,,
cowidev.vax.incremental.turkey,40.03,False,2023-01-25T07:07:03,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1042, in _validate_conn
    conn.connect()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    self.sock = conn = self._new_conn()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f2818325b10>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2818325b10>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2818325b10>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2818325b10>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2023-01-25T07:00:30,,
cowidev.vax.incremental.vietnam,,,2023-01-25T07:00:30,,
cowidev.vax.incremental.who,62.4,True,2023-01-25T07:01:33,,
cowidev.vax.incremental.zambia,1.24,True,2023-01-25T07:00:32,,
