module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.65,True,2022-11-21T07:00:14,,
cowidev.vax.batch.australia,,,2022-11-21T07:00:11,,
cowidev.vax.batch.austria,1.83,True,2022-11-21T07:00:12,,
cowidev.vax.batch.belgium,2.18,True,2022-11-21T07:00:13,,
cowidev.vax.batch.bolivia,2.04,True,2022-11-21T07:00:13,,
cowidev.vax.batch.canada,6.76,True,2022-11-21T07:00:17,,
cowidev.vax.batch.chile,0.95,True,2022-11-21T07:00:13,,
cowidev.vax.batch.czechia,4.75,True,2022-11-21T07:00:17,,
cowidev.vax.batch.denmark,5.33,True,2022-11-21T07:00:18,,
cowidev.vax.batch.ecdc,25.21,True,2022-11-21T15:20:54,,
cowidev.vax.batch.ecuador,1.6,True,2022-11-21T07:00:16,,
cowidev.vax.batch.estonia,0.95,True,2022-11-21T07:00:17,,
cowidev.vax.batch.france,0.69,True,2022-11-21T07:00:18,,
cowidev.vax.batch.germany,1.73,True,2022-11-21T07:00:19,,
cowidev.vax.batch.greece,3.14,True,2022-11-21T07:00:21,,
cowidev.vax.batch.hong_kong,13.5,True,2022-11-21T07:00:31,,
cowidev.vax.batch.indonesia,,,2022-11-21T07:00:18,,
cowidev.vax.batch.ireland,0.21,True,2022-11-21T07:00:18,,
cowidev.vax.batch.israel,11.57,True,2022-11-21T07:00:30,,
cowidev.vax.batch.italy,13.07,True,2022-11-21T07:00:32,,
cowidev.vax.batch.japan,19.78,False,2022-11-21T07:05:22,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 237, in main
    Japan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 221, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 157, in read
    df_latest = self.read_latest().pipe(self.pipe_latest)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 90, in read_latest
    dfs.append(self._read_xlsx(self.source_url_bst, self.sheets_bst, self.metrics_bst))
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 98, in _read_xlsx
    xlsx = pd.ExcelFile(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1191, in __init__
    ext = inspect_excel_format(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1070, in inspect_excel_format
    with get_handle(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 609, in get_handle
    ioargs = _get_filepath_or_buffer(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 312, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 212, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 214, in urlopen
    return opener.open(url, data, timeout)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 523, in open
    response = meth(req, response)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 632, in http_response
    response = self.parent.error(
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 561, in error
    return self._call_chain(*args)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 494, in _call_chain
    result = func(*args)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/urllib/request.py"", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
",HTTP Error 404: Not Found
cowidev.vax.batch.jersey,2.16,True,2022-11-21T07:00:32,,
cowidev.vax.batch.latvia,31.91,True,2022-11-21T07:01:03,,
cowidev.vax.batch.lithuania,1.75,True,2022-11-21T07:00:34,,
cowidev.vax.batch.luxembourg,2.43,True,2022-11-21T07:00:35,,
cowidev.vax.batch.malaysia,2.41,True,2022-11-21T07:00:36,,
cowidev.vax.batch.malta,1.38,True,2022-11-21T07:00:36,,
cowidev.vax.batch.netherlands,,,2022-11-21T07:00:36,,
cowidev.vax.batch.new_zealand,11.15,True,2022-11-21T07:00:47,,
cowidev.vax.batch.norway,2.2,True,2022-11-21T07:00:38,,
cowidev.vax.batch.peru,3.98,True,2022-11-21T07:00:42,,
cowidev.vax.batch.portugal,,,2022-11-21T07:00:42,,
cowidev.vax.batch.romania,8.86,True,2022-11-21T07:00:51,,
cowidev.vax.batch.saudi_arabia,3.35,True,2022-11-21T07:00:51,,
cowidev.vax.batch.singapore,0.87,True,2022-11-21T17:06:47,,
cowidev.vax.batch.slovakia,54.21,True,2022-11-21T07:01:46,,
cowidev.vax.batch.slovenia,2.73,True,2022-11-21T07:01:01,,
cowidev.vax.batch.south_korea,23.48,True,2022-11-21T07:01:24,,
cowidev.vax.batch.spc,13.2,True,2022-11-21T07:01:16,,
cowidev.vax.batch.sweden,,,2022-11-21T07:01:10,,
cowidev.vax.batch.switzerland,37.92,True,2022-11-21T07:01:48,,
cowidev.vax.batch.trinidad_and_tobago,1.77,True,2022-11-21T07:01:18,,
cowidev.vax.batch.ukraine,,,2022-11-21T07:01:18,,
cowidev.vax.batch.united_kingdom,9.27,True,2022-11-21T07:01:27,,
cowidev.vax.batch.united_states,29.7,True,2022-11-21T07:01:54,,
cowidev.vax.batch.uruguay,3.2,True,2022-11-21T07:01:30,,
cowidev.vax.batch.zimbabwe,1.96,True,2022-11-21T07:01:32,,
cowidev.vax.incremental.africacdc,,,2022-11-21T07:01:32,,
cowidev.vax.incremental.antigua_barbuda,,,2022-11-21T07:01:32,,
cowidev.vax.incremental.aruba,0.88,True,2022-11-21T07:01:33,,
cowidev.vax.incremental.azerbaijan,,,2022-11-21T07:01:33,,
cowidev.vax.incremental.bahrain,3.91,True,2022-11-21T07:01:37,,
cowidev.vax.incremental.bangladesh,26.8,True,2022-11-21T07:02:02,,
cowidev.vax.incremental.barbados,,,2022-11-21T07:01:37,,
cowidev.vax.incremental.brazil,0.42,True,2022-11-21T07:01:38,,
cowidev.vax.incremental.bulgaria,7.71,True,2022-11-21T07:01:45,,
cowidev.vax.incremental.china,34.19,True,2022-11-21T16:34:36,,
cowidev.vax.incremental.costa_rica,,,2022-11-21T07:01:46,,
cowidev.vax.incremental.croatia,0.15,True,2022-11-21T07:01:46,,
cowidev.vax.incremental.cuba,2.49,True,2022-11-21T07:01:48,,
cowidev.vax.incremental.curacao,0.4,True,2022-11-21T07:01:48,,
cowidev.vax.incremental.cyprus,0.73,True,2022-11-21T07:01:49,,
cowidev.vax.incremental.dominican_republic,8.75,True,2022-11-21T07:01:57,,
cowidev.vax.incremental.el_salvador,4.49,True,2022-11-21T07:01:53,,
cowidev.vax.incremental.faeroe_islands,0.57,True,2022-11-21T07:01:54,,
cowidev.vax.incremental.fiji,0.0,True,2022-11-21T07:01:54,,
cowidev.vax.incremental.finland,0.26,True,2022-11-21T07:01:54,,
cowidev.vax.incremental.gabon,,,2022-11-21T07:01:54,,
cowidev.vax.incremental.georgia,0.56,True,2022-11-21T07:01:55,,
cowidev.vax.incremental.greenland,0.45,False,2022-11-21T07:07:03,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 74, in main
    Greenland().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 61, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 18, in read
    data = self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 22, in _parse_data
    return {**self._parse_data_metrics(soup), **self._parse_data_date(soup)}
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 26, in _parse_data_metrics
    dose_1 = clean_count(re.search(r""Innuttaasut ([\d\.]+)"", counters[1].parent.find_all(""dd"")[-1].text).group(1))
IndexError: list index out of range
",list index out of range
cowidev.vax.incremental.guatemala,,,2022-11-21T07:01:55,,
cowidev.vax.incremental.guernsey,0.37,False,2022-11-21T07:07:04,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 61, in main
    Guernsey().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 50, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 15, in read
    df = self.parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 31, in parse_data
    ds.loc[ds[0] == ""Total doses"", 1].values[0].replace(""*"", """"),
IndexError: index 0 is out of bounds for axis 0 with size 0
",index 0 is out of bounds for axis 0 with size 0
cowidev.vax.incremental.hungary,1.07,True,2022-11-21T07:01:56,,
cowidev.vax.incremental.iceland,0.74,True,2022-11-21T07:01:56,,
cowidev.vax.incremental.india,0.89,True,2022-11-21T07:01:57,,
cowidev.vax.incremental.iran,,,2022-11-21T07:01:56,,
cowidev.vax.incremental.isle_of_man,0.68,True,2022-11-21T07:01:56,,
cowidev.vax.incremental.jamaica,1.91,True,2022-11-21T07:01:58,,
cowidev.vax.incremental.kazakhstan,13.28,True,2022-11-21T07:02:10,,
cowidev.vax.incremental.kosovo,1.6,True,2022-11-21T07:01:59,,
cowidev.vax.incremental.kyrgyzstan,2.85,True,2022-11-21T07:02:01,,
cowidev.vax.incremental.laos,2.18,True,2022-11-21T07:02:01,,
cowidev.vax.incremental.macao,30.82,False,2022-11-21T07:07:34,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 86, in main
    Macao().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 72, in export
    data = self.read()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 22, in read
    data = self._parse_data(elem)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 50, in _parse_data
    df = self._parse_pdf_table(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 33, in _parse_pdf_table
    raise ValueError(""New columns added!"")
ValueError: New columns added!
",New columns added!
cowidev.vax.incremental.moldova,,,2022-11-21T07:02:01,,
cowidev.vax.incremental.monaco,30.48,True,2022-11-21T07:02:32,,
cowidev.vax.incremental.mongolia,0.71,True,2022-11-21T07:02:02,,
cowidev.vax.incremental.montenegro,0.15,True,2022-11-21T07:02:03,,
cowidev.vax.incremental.morocco,,,2022-11-21T07:02:03,,
cowidev.vax.incremental.myanmar,,,2022-11-21T07:02:03,,
cowidev.vax.incremental.nepal,,,2022-11-21T07:02:03,,
cowidev.vax.incremental.north_macedonia,,,2022-11-21T07:02:03,,
cowidev.vax.incremental.northern_cyprus,0.77,True,2022-11-21T07:02:03,,
cowidev.vax.incremental.paho,49.87,True,2022-11-21T15:21:19,,
cowidev.vax.incremental.pakistan,1.33,True,2022-11-21T07:02:11,,
cowidev.vax.incremental.philippines,,,2022-11-21T07:02:11,,
cowidev.vax.incremental.playground_mojmir,4.96,True,2022-11-21T07:02:16,,
cowidev.vax.incremental.poland,0.32,True,2022-11-21T07:02:16,,
cowidev.vax.incremental.qatar,,,2022-11-21T07:02:16,,
cowidev.vax.incremental.russia,1.2,True,2022-11-21T15:20:30,,
cowidev.vax.incremental.saint_lucia,,,2022-11-21T07:02:17,,
cowidev.vax.incremental.serbia,6.39,True,2022-11-21T07:02:23,,
cowidev.vax.incremental.south_africa,7.91,True,2022-11-21T07:02:31,,
cowidev.vax.incremental.spain,14.82,True,2022-11-21T07:02:46,,
cowidev.vax.incremental.sri_lanka,,,2022-11-21T07:02:32,,
cowidev.vax.incremental.suriname,16.07,True,2022-11-21T07:02:48,,
cowidev.vax.incremental.taiwan,4.92,True,2022-11-21T16:32:59,,
cowidev.vax.incremental.thailand,4.17,True,2022-11-21T07:02:50,,
cowidev.vax.incremental.turkey,40.05,False,2022-11-21T07:09:44,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fe62d3a0040>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe62d3a0040>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe62d3a0040>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe62d3a0040>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2022-11-21T07:02:48,,
cowidev.vax.incremental.vietnam,,,2022-11-21T07:02:48,,
cowidev.vax.incremental.who,4.25,True,2022-11-21T07:02:52,,
cowidev.vax.incremental.zambia,0.88,True,2022-11-21T07:02:51,,
