module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,16.18,True,2022-12-13T07:00:22,,
cowidev.vax.batch.australia,137.76,True,2022-12-13T07:02:23,,
cowidev.vax.batch.austria,12.83,True,2022-12-13T07:00:18,,
cowidev.vax.batch.belgium,6.91,True,2022-12-13T07:00:13,,
cowidev.vax.batch.bolivia,4.86,True,2022-12-13T07:00:10,,
cowidev.vax.batch.canada,4.05,True,2022-12-13T10:27:05,,
cowidev.vax.batch.chile,1.6,True,2022-12-13T07:00:07,,
cowidev.vax.batch.czechia,1.77,True,2022-12-13T07:00:07,,
cowidev.vax.batch.denmark,141.87,True,2022-12-13T07:02:27,,
cowidev.vax.batch.ecdc,145.47,True,2022-12-13T07:02:31,,
cowidev.vax.batch.ecuador,,,2022-12-13T07:00:06,,
cowidev.vax.batch.estonia,0.73,True,2022-12-13T07:00:06,,
cowidev.vax.batch.france,7.35,True,2022-12-13T07:00:13,,
cowidev.vax.batch.germany,0.21,True,2022-12-13T07:00:06,,
cowidev.vax.batch.greece,20.71,True,2022-12-13T07:00:26,,
cowidev.vax.batch.hong_kong,22.73,True,2022-12-13T07:00:28,,
cowidev.vax.batch.indonesia,,,2022-12-13T07:00:06,,
cowidev.vax.batch.ireland,6.31,True,2022-12-13T07:00:12,,
cowidev.vax.batch.israel,16.58,True,2022-12-13T07:00:22,,
cowidev.vax.batch.italy,11.14,True,2022-12-13T07:00:17,,
cowidev.vax.batch.japan,59.04,True,2022-12-13T07:01:05,,
cowidev.vax.batch.jersey,6.86,True,2022-12-13T07:00:12,,
cowidev.vax.batch.latvia,71.34,True,2022-12-13T07:01:17,,
cowidev.vax.batch.lithuania,7.1,True,2022-12-13T07:00:13,,
cowidev.vax.batch.luxembourg,4.24,True,2022-12-13T07:00:10,,
cowidev.vax.batch.malaysia,0.92,True,2022-12-13T07:00:07,,
cowidev.vax.batch.malta,1.05,True,2022-12-13T07:00:07,,
cowidev.vax.batch.netherlands,,,2022-12-13T07:00:06,,
cowidev.vax.batch.new_zealand,10.01,True,2022-12-13T07:00:16,,
cowidev.vax.batch.norway,0.62,True,2022-12-13T07:00:06,,
cowidev.vax.batch.peru,0.42,False,2022-12-13T10:20:49,"Traceback (most recent call last):
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/batch/peru.py"", line 167, in main
    Peru().export()
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/batch/peru.py"", line 145, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/batch/peru.py"", line 92, in pipeline
    .pipe(self.pipe_filter_only_campaign)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/lucas/repos/covid-19-data/scripts/src/cowidev/vax/batch/peru.py"", line 48, in pipe_filter_only_campaign
    return df.drop(columns=[""flag_vacunacion_general""])
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/frame.py"", line 4906, in drop
    return super().drop(
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File ""/home/lucas/repos/covid-19-data/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py"", line 6017, in drop
    raise KeyError(f""{labels[mask]} not found in axis"")
KeyError: ""['flag_vacunacion_general'] not found in axis""
","""['flag_vacunacion_general'] not found in axis"""
cowidev.vax.batch.portugal,,,2022-12-13T07:00:06,,
cowidev.vax.batch.romania,55.43,True,2022-12-13T07:01:01,,
cowidev.vax.batch.saudi_arabia,16.04,True,2022-12-13T07:00:22,,
cowidev.vax.batch.singapore,5.58,True,2022-12-13T07:00:11,,
cowidev.vax.batch.slovakia,128.07,True,2022-12-13T07:02:14,,
cowidev.vax.batch.slovenia,3.5,True,2022-12-13T07:00:10,,
cowidev.vax.batch.south_korea,140.9,True,2022-12-13T07:02:27,,
cowidev.vax.batch.spc,31.68,True,2022-12-13T07:00:38,,
cowidev.vax.batch.sweden,21.73,True,2022-12-13T07:00:28,,
cowidev.vax.batch.switzerland,142.3,True,2022-12-13T07:02:29,,
cowidev.vax.batch.trinidad_and_tobago,5.46,True,2022-12-13T07:00:13,,
cowidev.vax.batch.ukraine,,,2022-12-13T07:00:07,,
cowidev.vax.batch.united_kingdom,20.42,True,2022-12-13T07:00:28,,
cowidev.vax.batch.united_states,141.94,True,2022-12-13T07:02:32,,
cowidev.vax.batch.uruguay,8.94,True,2022-12-13T07:00:19,,
cowidev.vax.batch.zimbabwe,2.21,True,2022-12-13T07:00:13,,
cowidev.vax.incremental.africacdc,,,2022-12-13T07:00:11,,
cowidev.vax.incremental.antigua_barbuda,,,2022-12-13T07:00:11,,
cowidev.vax.incremental.aruba,1.51,True,2022-12-13T07:00:13,,
cowidev.vax.incremental.azerbaijan,,,2022-12-13T07:00:12,,
cowidev.vax.incremental.bahrain,8.33,True,2022-12-13T07:00:20,,
cowidev.vax.incremental.bangladesh,35.46,True,2022-12-13T07:00:48,,
cowidev.vax.incremental.barbados,,,2022-12-13T07:00:13,,
cowidev.vax.incremental.brazil,1.09,True,2022-12-13T07:00:14,,
cowidev.vax.incremental.bulgaria,13.16,True,2022-12-13T07:00:26,,
cowidev.vax.incremental.china,41.74,True,2022-12-13T07:00:54,,
cowidev.vax.incremental.costa_rica,,,2022-12-13T07:00:13,,
cowidev.vax.incremental.croatia,1.08,True,2022-12-13T07:00:14,,
cowidev.vax.incremental.cuba,22.31,True,2022-12-13T07:00:35,,
cowidev.vax.incremental.curacao,1.38,True,2022-12-13T07:00:14,,
cowidev.vax.incremental.cyprus,4.23,True,2022-12-13T07:00:18,,
cowidev.vax.incremental.dominican_republic,12.76,True,2022-12-13T10:17:29,,
cowidev.vax.incremental.el_salvador,15.44,True,2022-12-13T07:00:30,,
cowidev.vax.incremental.faeroe_islands,2.42,True,2022-12-13T07:00:18,,
cowidev.vax.incremental.fiji,0.0,True,2022-12-13T07:00:17,,
cowidev.vax.incremental.finland,1.06,True,2022-12-13T07:00:18,,
cowidev.vax.incremental.gabon,,,2022-12-13T07:00:18,,
cowidev.vax.incremental.georgia,9.71,True,2022-12-13T07:00:28,,
cowidev.vax.incremental.greenland,5.09,True,2022-12-13T07:00:23,,
cowidev.vax.incremental.guatemala,,,2022-12-13T07:00:18,,
cowidev.vax.incremental.guernsey,11.39,True,2022-12-13T07:00:29,,
cowidev.vax.incremental.hungary,6.73,True,2022-12-13T07:00:25,,
cowidev.vax.incremental.iceland,5.27,True,2022-12-13T07:00:24,,
cowidev.vax.incremental.india,3.43,True,2022-12-13T07:00:24,,
cowidev.vax.incremental.iran,,,2022-12-13T07:00:22,,
cowidev.vax.incremental.isle_of_man,3.27,True,2022-12-13T07:00:25,,
cowidev.vax.incremental.jamaica,10.72,True,2022-12-13T07:00:32,,
cowidev.vax.incremental.kazakhstan,10.27,True,2022-12-13T07:00:32,,
cowidev.vax.incremental.kosovo,8.05,True,2022-12-13T07:00:31,,
cowidev.vax.incremental.kyrgyzstan,6.29,True,2022-12-13T07:00:30,,
cowidev.vax.incremental.laos,8.85,True,2022-12-13T07:00:33,,
cowidev.vax.incremental.macao,12.44,True,2022-12-13T07:00:37,,
cowidev.vax.incremental.moldova,,,2022-12-13T07:00:25,,
cowidev.vax.incremental.monaco,135.92,True,2022-12-13T07:02:41,,
cowidev.vax.incremental.mongolia,1.35,True,2022-12-13T07:00:27,,
cowidev.vax.incremental.montenegro,1.01,True,2022-12-13T07:00:27,,
cowidev.vax.incremental.morocco,,,2022-12-13T07:00:27,,
cowidev.vax.incremental.myanmar,,,2022-12-13T07:00:27,,
cowidev.vax.incremental.nepal,,,2022-12-13T07:00:27,,
cowidev.vax.incremental.north_macedonia,,,2022-12-13T07:00:27,,
cowidev.vax.incremental.northern_cyprus,5.49,True,2022-12-13T07:00:33,,
cowidev.vax.incremental.paho,75.67,True,2022-12-13T10:18:32,,
cowidev.vax.incremental.pakistan,5.9,False,2022-12-13T07:06:52,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1042, in _validate_conn
    conn.connect()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 414, in connect
    self.sock = ssl_wrap_socket(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py"", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py"", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File ""/usr/lib/python3.10/ssl.py"", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File ""/usr/lib/python3.10/ssl.py"", line 1071, in _create
    self.do_handshake()
  File ""/usr/lib/python3.10/ssl.py"", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid.gov.pk', port=443): Max retries exceeded with url: /vaccine-details (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/pakistan.py"", line 58, in main
    Pakistan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/pakistan.py"", line 53, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/pakistan.py"", line 17, in read
    soup = get_soup(self.source_url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='covid.gov.pk', port=443): Max retries exceeded with url: /vaccine-details (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
","HTTPSConnectionPool(host='covid.gov.pk', port=443): Max retries exceeded with url: /vaccine-details (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))"
cowidev.vax.incremental.philippines,,,2022-12-13T07:00:28,,
cowidev.vax.incremental.poland,1.71,True,2022-12-13T07:00:30,,
cowidev.vax.incremental.qatar,,,2022-12-13T07:00:28,,
cowidev.vax.incremental.russia,62.78,True,2022-12-13T07:01:31,,
cowidev.vax.incremental.saint_lucia,,,2022-12-13T07:00:28,,
cowidev.vax.incremental.serbia,8.41,True,2022-12-13T07:00:37,,
cowidev.vax.incremental.south_africa,9.02,True,2022-12-13T07:00:38,,
cowidev.vax.incremental.spain,26.32,True,2022-12-13T07:00:56,,
cowidev.vax.incremental.sri_lanka,,,2022-12-13T07:00:30,,
cowidev.vax.incremental.suriname,15.47,True,2022-12-13T07:00:45,,
cowidev.vax.incremental.taiwan,38.89,True,2022-12-13T07:01:09,,
cowidev.vax.incremental.thailand,7.07,True,2022-12-13T07:00:37,,
cowidev.vax.incremental.turkey,40.03,False,2022-12-13T07:07:32,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 95, in create_connection
    raise err
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/connection.py"", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1042, in _validate_conn
    conn.connect()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 358, in connect
    self.sock = conn = self._new_conn()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f09eb554970>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09eb554970>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 46, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09eb554970>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='covid19asi.saglik.gov.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09eb554970>, 'Connection to covid19asi.saglik.gov.tr timed out. (connect timeout=20)'))"
cowidev.vax.incremental.united_arab_emirates,,,2022-12-13T07:00:32,,
cowidev.vax.incremental.vietnam,,,2022-12-13T07:00:32,,
cowidev.vax.incremental.who,64.0,True,2022-12-13T07:01:36,,
cowidev.vax.incremental.zambia,1.15,True,2022-12-13T07:00:34,,
